const users = [
    { id: 1, name: "Emily Johnson", email: "emily.johnson@example.com", dateCreated: "2024-11-01", status: "active" },
    { id: 2, name: "James Smith", email: "james.smith@example.com", dateCreated: "2024-11-03", status: "suspended" },
    { id: 3, name: "Olivia Brown", email: "olivia.brown@example.com", dateCreated: "2024-11-05", status: "active" },
    { id: 4, name: "Liam Davis", email: "liam.davis@example.com", dateCreated: "2024-11-06", status: "active" },
    { id: 6, name: "Sophia Miller", email: "sophia.miller@example.com", dateCreated: "2024-11-07", status: "suspended" },
    { id: 7, name: "Noah Wilson", email: "noah.wilson@example.com", dateCreated: "2024-11-08", status: "active" },
    { id: 8, name: "Isabella Moore", email: "isabella.moore@example.com", dateCreated: "2024-11-09", status: "active" },
    { id: 9, name: "Mason Taylor", email: "mason.taylor@example.com", dateCreated: "2024-11-10", status: "suspended" },
    { id: 10, name: "Ava Anderson", email: "ava.anderson@example.com", dateCreated: "2024-11-11", status: "active" },
    { id: 11, name: "Lucas Thomas", email: "lucas.thomas@example.com", dateCreated: "2024-11-12", status: "active" },
    { id: 12, name: "Mia Jackson", email: "mia.jackson@example.com", dateCreated: "2024-11-13", status: "suspended" },
    { id: 13, name: "Ethan White", email: "ethan.white@example.com", dateCreated: "2024-11-14", status: "active" },
    { id: 14, name: "Amelia Harris", email: "amelia.harris@example.com", dateCreated: "2024-11-15", status: "active" },
    { id: 15, name: "Logan Martin", email: "logan.martin@example.com", dateCreated: "2024-11-16", status: "suspended" },
    { id: 16, name: "Charlotte Thompson", email: "charlotte.thompson@example.com", dateCreated: "2024-11-17", status: "active" },
    { id: 17, name: "Jacob Garcia", email: "jacob.garcia@example.com", dateCreated: "2024-11-18", status: "active" },
    { id: 18, name: "Harper Martinez", email: "harper.martinez@example.com", dateCreated: "2024-11-19", status: "suspended" },
    { id: 19, name: "Michael Robinson", email: "michael.robinson@example.com", dateCreated: "2024-11-20", status: "active" },
    { id: 21,name: "Ella Clark", email: "ella.clark@example.com", dateCreated: "2024-11-21", status: "active" },
    { id: 22,name: "Benjamin Rodriguez", email: "benjamin.rodriguez@example.com", dateCreated: "2024-11-22", status: "suspended" },
    { id: 23,name: "Abigail Lewis", email: "abigail.lewis@example.com", dateCreated: "2024-11-23", status: "active" },
    { id: 24,name: "Henry Lee", email: "henry.lee@example.com", dateCreated: "2024-11-24", status: "active" },
    { id: 25, name: "Grace Walker", email: "grace.walker@example.com", dateCreated: "2024-11-25", status: "suspended" },
    { id: 26, name: "Daniel Hall", email: "daniel.hall@example.com", dateCreated: "2024-11-26", status: "active" },
    { id: 27, name: "Chloe Allen", email: "chloe.allen@example.com", dateCreated: "2024-11-27", status: "active" },
  ];

  const transactions = [
  {
    id: "#TXN1001",
    name: "Alice Morgan",
    amount: "$50",
    discount: "SAVE10",
    dueDate: "20 Mar 2025",
    status: "Paid",
    active: true,
  },
  {
    id: "#TXN1002",
    name: "James Smith",
    amount: "$75",
    discount: "NEW20",
    dueDate: "22 Mar 2025",
    status: "Pending",
    active: true,
  },
  {
    id: "#TXN1003",
    name: "Olivia Johnson",
    amount: "$100",
    discount: "SAVE10",
    dueDate: "18 Mar 2025",
    status: "Paid",
    active: false,
  },
  {
    id: "#TXN1004",
    name: "Liam Brown",
    amount: "$35",
    discount: "OFF5",
    dueDate: "21 Mar 2025",
    status: "Overdue",
    active: true,
  },
  {
    id: "#TXN1005",
    name: "Emma Davis",
    amount: "$60",
    discount: "SAVE10",
    dueDate: "25 Mar 2025",
    status: "Paid",
    active: false,
  },
  {
    id: "#TXN1006",
    name: "Noah Wilson",
    amount: "$45",
    discount: "SAVE10",
    dueDate: "20 Mar 2025",
    status: "Pending",
    active: true,
  },
  {
    id: "#TXN1007",
    name: "Ava Taylor",
    amount: "$70",
    discount: "NEW20",
    dueDate: "24 Mar 2025",
    status: "Paid",
    active: true,
  },
  {
    id: "#TXN1008",
    name: "Elijah Anderson",
    amount: "$90",
    discount: "SAVE10",
    dueDate: "19 Mar 2025",
    status: "Overdue",
    active: false,
  },
  {
    id: "#TXN1009",
    name: "Sophia Thomas",
    amount: "$55",
    discount: "OFF5",
    dueDate: "23 Mar 2025",
    status: "Paid",
    active: true,
  },
  {
    id: "#TXN1010",
    name: "Mason Jackson",
    amount: "$80",
    discount: "SAVE10",
    dueDate: "20 Mar 2025",
    status: "Pending",
    active: false,
  },
  {
    id: "#TXN1011",
    name: "Isabella White",
    amount: "$40",
    discount: "SAVE10",
    dueDate: "21 Mar 2025",
    status: "Paid",
    active: true,
  },
  {
    id: "#TXN1012",
    name: "Logan Harris",
    amount: "$30",
    discount: "NEW20",
    dueDate: "22 Mar 2025",
    status: "Overdue",
    active: false,
  },
  {
    id: "#TXN1013",
    name: "Mia Martin",
    amount: "$65",
    discount: "SAVE10",
    dueDate: "18 Mar 2025",
    status: "Paid",
    active: true,
  },
  {
    id: "#TXN1014",
    name: "Lucas Thompson",
    amount: "$75",
    discount: "SAVE10",
    dueDate: "20 Mar 2025",
    status: "Pending",
    active: false,
  },
  {
    id: "#TXN1015",
    name: "Charlotte Garcia",
    amount: "$85",
    discount: "OFF5",
    dueDate: "19 Mar 2025",
    status: "Paid",
    active: true,
  },
  {
    id: "#TXN1016",
    name: "Henry Martinez",
    amount: "$55",
    discount: "SAVE10",
    dueDate: "23 Mar 2025",
    status: "Overdue",
    active: false,
  },
  {
    id: "#TXN1017",
    name: "Amelia Robinson",
    amount: "$95",
    discount: "SAVE10",
    dueDate: "25 Mar 2025",
    status: "Paid",
    active: true,
  },
  {
    id: "#TXN1018",
    name: "Benjamin Clark",
    amount: "$60",
    discount: "NEW20",
    dueDate: "21 Mar 2025",
    status: "Pending",
    active: true,
  },
  {
    id: "#TXN1019",
    name: "Evelyn Rodriguez",
    amount: "$40",
    discount: "SAVE10",
    dueDate: "22 Mar 2025",
    status: "Overdue",
    active: false,
  },
  {
    id: "#TXN1020",
    name: "Jack Lewis",
    amount: "$50",
    discount: "SAVE10",
    dueDate: "20 Mar 2025",
    status: "Paid",
    active: true,
  },
  {
    id: "#TXN1021",
    name: "Harper Lee",
    amount: "$70",
    discount: "OFF5",
    dueDate: "24 Mar 2025",
    status: "Paid",
    active: false,
  },
  {
    id: "#TXN1022",
    name: "Sebastian Walker",
    amount: "$65",
    discount: "SAVE10",
    dueDate: "23 Mar 2025",
    status: "Pending",
    active: true,
  },
  {
    id: "#TXN1023",
    name: "Abigail Hall",
    amount: "$90",
    discount: "NEW20",
    dueDate: "25 Mar 2025",
    status: "Paid",
    active: true,
  },
  {
    id: "#TXN1024",
    name: "Daniel Allen",
    amount: "$85",
    discount: "SAVE10",
    dueDate: "19 Mar 2025",
    status: "Overdue",
    active: false,
  },
  {
    id: "#TXN1025",
    name: "Ella Young",
    amount: "$55",
    discount: "SAVE10",
    dueDate: "21 Mar 2025",
    status: "Paid",
    active: true,
  },
];

const billingHistory = [
  {
    invoiceNo: "#664f66ee8",
    name: "John Miles",
    status: "Paid",
    issuedDate: "23/05/2024, 20:55:26",
    date: "22/06/2024, 00:00:00",
    amount: "£50",
  },
  {
    invoiceNo: "#664f66ee8",
    name: "John Miles",
    status: "Pending",
    issuedDate: "23/05/2024, 20:55:26",
    date: "22/06/2024, 00:00:00",
    amount: "£50",
  },
  {
    invoiceNo: "#664f66ee8",
    name: "John Miles",
    status: "Paid",
    issuedDate: "23/05/2024, 20:55:26",
    date: "22/06/2024, 00:00:00",
    amount: "£50",
  },
  {
    invoiceNo: "#664f66ee8",
    name: "John Miles",
    status: "Paid",
    issuedDate: "23/05/2024, 20:55:26",
    date: "22/06/2024, 00:00:00",
    amount: "£50",
  },
  {
    invoiceNo: "#664f66ee8",
    name: "John Miles",
    status: "Paid",
    issuedDate: "23/05/2024, 20:55:26",
    date: "22/06/2024, 00:00:00",
    amount: "£50",
  },
]

const BarChatData = [
  {
    "name": "Page A",
    "uv": 4000,
    "pv": 2400
  },
  {
    "name": "Page B",
    "uv": 3000,
    "pv": 1398
  },
  {
    "name": "Page C",
    "uv": 2000,
    "pv": 9800
  },
  {
    "name": "Page D",
    "uv": 2780,
    "pv": 3908
  },
  {
    "name": "Page E",
    "uv": 1890,
    "pv": 4800
  },
  {
    "name": "Page F",
    "uv": 2390,
    "pv": 3800
  },
  {
    "name": "Page G",
    "uv": 3490,
    "pv": 4300
  }
]




export {users, transactions, billingHistory, BarChatData}